function B = bancoIE()
%BANCOIE Banco de preguntas de opcion multiple de Electrica II.
%   B = bancoIE() devuelve un arreglo struct 1x72 con los campos id,
%   tema, enunciado, opciones (1x4 cell), correcta (1..4), explicacion,
%   bandera y advertencia. Uso:  B = bancoIE();  disp(numel(B))

C = {
 't1p01','Transformadores','Cual es la funcion principal de un transformador electrico?',{'Convertir la energia mecanica del rotor en energia electrica.','Transferir energia entre circuitos mediante induccion electromagnetica.','Almacenar energia reactiva y regular la tension en la red.','Rectificar la corriente alterna para alimentar cargas continuas de baja tension.'},2,'El transformador transfiere energia entre circuitos por induccion electromagnetica y conserva la frecuencia. La variante que lo presenta como maquina que convierte energia mecanica cae porque eso describe al generador, no al transformador.',false,'';
 't1p02','Transformadores','Que permite modificar un transformador?',{'La frecuencia de operacion y la fase, manteniendo constante el nivel de tension.','Los niveles de tension y corriente, idealmente sin cambiar la frecuencia.','Solo la tension, sin alterar la corriente ni la frecuencia.','La potencia activa, dejando intactas la tension y la frecuencia.'},2,'El transformador modifica tension y corriente de forma idealmente inversa, pero conserva la frecuencia. El distractor que le atribuye cambiar la frecuencia falla porque eso lo haria un convertidor de frecuencia, no un transformador.',false,'';
 't1p03','Transformadores','Para que se utilizan los transformadores de distribucion?',{'Para elevar la tension a niveles de transmision de larga distancia.','Para convertir la corriente alterna en corriente continua.','Para compensar el factor de potencia de las instalaciones.','Para reducir la tension a niveles adecuados para los consumidores.'},4,'Los transformadores de distribucion bajan la tension desde el nivel de media a un nivel seguro para los consumidores. Elevar la tension a niveles de transmision es funcion de los transformadores de potencia, por eso ese distractor no aplica aqui.',false,'';
 't1p04','Transformadores','Que tipos de transformadores de distribucion hay?',{'CSP y convencionales.','De potencia y de medida.','Elevadores y rectificadores.','De instrumento y de medida.'},1,'El documento clasifica los transformadores de distribucion en CSP, con protecciones integradas, y convencionales, con protecciones externas. La opcion de potencia y de medida confunde estos equipos con transformadores de potencia y de instrumentacion, que no son tipos de distribucion.',false,'';
 't1p05','Transformadores','Que significa CSP?',{'Common Safety Protection.','Continuous Surge Protection.','Completely Self-Protected.','Core Shielded Primary.'},3,'CSP es la sigla de Completely Self-Protected, el transformador de distribucion con protecciones integradas. La variante Continuous Surge Protection suena tecnica, pero no corresponde a la sigla del curso.',false,'';
 't1p06','Transformadores','Que protecciones incorpora un transformador CSP?',{'Fusible primario, interruptor automatico secundario y descargadores de sobretension.','Fusible secundario, interruptor automatico primario y pararrayos de linea.','Rele diferencial, seccionador de puesta a tierra y fusibles de acometida.','Descargadores de sobretension, seccionador de carga y fusibles de distribucion.'},1,'El CSP integra fusible primario, interruptor automatico secundario y descargadores de sobretension. La variante que intercambia primario y secundario es falsa porque el fusible protege el lado primario y el interruptor automatico actua en el secundario.',false,'';
 't1p07','Transformadores','Donde suelen instalarse los transformadores CSP?',{'En subestaciones blindadas bajo techo y servicio interior.','En bovedas subterraneas para servicio interior.','Generalmente en postes y para servicio exterior.','En salas electricas con ventilacion forzada.'},3,'Los CSP se instalan tipicamente en postes, a la intemperie, porque su proteccion integrada esta disenada para servicio exterior. La opcion de bovedas subterraneas corresponde a equipos de servicio interior, no al uso normal del CSP.',false,'';
 't1p08','Transformadores','Cual es la diferencia entre un CSP y uno convencional?',{'El CSP usa protecciones externas, el convencional las tiene integradas.','El CSP es monofasico y el convencional siempre es trifasico, sin importar la carga.','El CSP no requiere fusibles y el convencional si los necesita.','El CSP tiene protecciones integradas, el convencional utiliza protecciones externas.'},4,'La diferencia es que el CSP trae las protecciones incorporadas y el convencional depende de protecciones externas. El distractor que invierte los papeles es el mas tentador, pero el CSP es justamente el que integra fusible, interruptor automatico y descargadores.',false,'';
 't1p09','Transformadores','Donde se utilizan principalmente los transformadores de potencia?',{'En sistemas de generacion y transmision electrica.','En el alumbrado publico y las acometidas domiciliares.','En tableros de control y circuitos de instrumentacion.','En soldadoras y equipos de traccion de baja tension.'},1,'Los transformadores de potencia se usan en generacion y transmision, donde se manejan grandes bloques de potencia. El distractor de alumbrado publico y acometidas describe aplicaciones de transformadores de distribucion, no de potencia.',false,'';
 't1p10','Transformadores','Que funcion puede cumplir un transformador de potencia?',{'Puede cambiar la frecuencia de la red.','Puede convertir la corriente alterna en continua.','Puede elevar o reducir la tension.','Puede almacenar energia durante los picos de carga.'},3,'Un transformador de potencia puede elevar o reducir la tension segun la etapa del sistema. El distractor que le atribuye cambiar la frecuencia es falso porque el transformador conserva la frecuencia de la red.',false,'';
 't1p11','Transformadores','Por que elevar la tension reduce las perdidas?',{'Porque reduce la resistencia total de los conductores de linea.','Porque disminuye la potencia reactiva consumida por la carga conectada al final de la linea.','Porque aumenta la frecuencia de operacion del sistema.','Porque permite transportar la misma potencia con menor corriente.'},4,'Al elevar la tension, para la misma potencia la corriente baja, y las perdidas resistivas caen con el cuadrado de la corriente. El distractor que atribuye la mejora a una menor resistencia de linea confunde la causa: la resistencia no cambia, lo que cambia es la corriente.',false,'';
 't1p12','Transformadores','Que funciones cumple el fluido aislante?',{'Genera el campo magnetico y reduce las perdidas por histeresis.','Proporciona aislamiento electrico y ayuda a enfriar el equipo.','Lubrica las partes moviles y sella el nucleo magnetico.','Filtra las armonicas y regula la tension de salida.'},2,'El fluido aislante cumple doble funcion: aisla electricamente y transfiere calor para enfriar el equipo. El distractor que le asigna generar el campo magnetico es falso porque el campo magnetico lo establece el nucleo con los devanados, no el fluido.',false,'';
 't2p01','Medicion TP y TC','Que es un transformador de potencial?',{'Un transformador que reproduce en su secundario una corriente proporcional a la del primario, reducida a un nivel seguro para instrumentos de medida.','Un transformador que reproduce en su secundario una tension proporcional a la del primario, reducida a un nivel seguro para instrumentos.','Un transformador que convierte la corriente alterna del primario en corriente continua para instrumentos.','Un transformador que eleva la tension del primario a un nivel seguro para los instrumentos.'},2,'El TP reduce la tension del primario a un nivel proporcional y seguro para los instrumentos. El distractor que habla de corriente describe al transformador de corriente; esa es la confusion TP-TC mas comun.',false,'';
 't2p02','Medicion TP y TC','Cual es la relacion de tensiones en un TP y de corrientes en un TC?',{'Vp/Vs = Np/Ns y Ip/Is = Ns/Np.','Vp/Vs = Ns/Np y Ip/Is = Np/Ns.','Vp/Vs = Np/Ns y Ip/Is = Np/Ns.','Vp/Vs = Ns/Np y Ip/Is = Ns/Np.'},1,'La tension escala con la relacion de espiras y la corriente con su inversa: Vp/Vs = Np/Ns y Ip/Is = Ns/Np. El distractor que invierte ambas relaciones cae porque en el TC la corriente del secundario es mayor que la del primario cuando Ns es menor que Np.',false,'';
 't2p03','Medicion TP y TC','En que principio fisico se basan ambos transformadores?',{'En la conduccion electrica y la ley de Ohm.','En el efecto Joule y la ley de Kirchhoff de tensiones.','En la electrostatica de cargas en reposo y la ley de Coulomb para campos constantes.','En la induccion electromagnetica (leyes de Faraday y Ampere).'},4,'Ambos transformadores funcionan por induccion electromagnetica, descrita por las leyes de Faraday y Ampere. El distractor de conduccion y ley de Ohm confunde induccion con conduccion, que son fenomenos distintos.',false,'';
 't2p04','Medicion TP y TC','Como se conectan un TP y un TC al circuito?',{'El TP en serie con la linea cuya corriente se mide y el TC en paralelo con el circuito cuya tension se desea medir.','Ambos se conectan en serie con la linea monitoreada.','Ambos se conectan en paralelo con el circuito monitoreado.','El TP en paralelo con el circuito cuya tension se mide y el TC en serie con la linea cuya corriente se mide.'},4,'El TP se conecta en paralelo porque mide tension, y el TC en serie porque mide corriente. El distractor que los intercambia es tentador, pero dejaria el secundario del TC abierto o mediria mal ambas magnitudes.',false,'';
 't2p05','Medicion TP y TC','Como funciona el transformador de potencial inductivo?',{'Trabaja solo por induccion electromagnetica, con nucleo magnetico y devanados primario y secundario. Se usa en media y alta tension.','Reduce primero la tension con un divisor capacitivo, luego la pasa a un transformador inductivo de instrumentos y se usa en alta y muy alta tension.','Trabaja por acoplamiento capacitivo directo, sin nucleo magnetico ni devanados.','Trabaja por conduccion galvanica entre primario y secundario, sin nucleo ferromagnetico.'},1,'El TP inductivo trabaja unicamente por induccion, con nucleo y dos devanados, y se emplea en media y alta tension. El distractor del divisor capacitivo describe al TP capacitivo, que es otra tecnologia.',false,'';
 't2p06','Medicion TP y TC','Como funciona el transformador de potencial capacitivo?',{'Trabaja solo por induccion electromagnetica, con nucleo magnetico y devanados primario y secundario, y se usa en media y alta tension.','Reduce primero la tension con un divisor capacitivo y luego la pasa a un transformador inductivo. Se usa en alta y muy alta tension.','Eleva la tension con un divisor capacitivo y luego la entrega directa a los instrumentos.','Convierte la corriente de linea en tension mediante un shunt capacitivo.'},2,'El TP capacitivo reduce la tension en un divisor capacitivo y despues la entrega a un transformador inductivo, por eso se usa en alta y muy alta tension. El distractor que lo describe como puramente inductivo corresponde al TP inductivo.',false,'';
 't2p07','Medicion TP y TC','Segun su construccion, que dos tipos de TC existen y en que se diferencian?',{'El tipo inductivo, con nucleo magnetico y devanados, y el tipo capacitivo, con divisor de tension y transformador interno.','El tipo devanado, con primario de una espira, y el tipo barra, con varias espiras.','El tipo devanado, con primario de varias espiras, y el tipo barra o ventana, donde el propio conductor atraviesa el nucleo.','El tipo elevador de tension y el tipo reductor de tension, segun su relacion.'},3,'El TC tipo devanado tiene primario de varias espiras y el tipo barra o ventana usa el propio conductor atravesando el nucleo. El distractor que invierte el numero de espiras cae porque el tipo barra tiene una sola espira, no varias.',false,'';
 't2p08','Medicion TP y TC','Cuantas espiras tiene el primario de un TC tipo barra?',{'Dos espiras, una por cada mitad del nucleo.','Varias decenas, segun la relacion de transformacion.','Ninguna, porque el conductor no forma parte del devanado.','Una sola (Np = 1), el propio conductor.'},4,'En el TC tipo barra el primario es el propio conductor que atraviesa el nucleo, por eso equivale a una sola espira. El distractor de dos espiras es plausible pero falso: no hay una espira por cada mitad del nucleo.',false,'';
 't2p09','Medicion TP y TC','Cuando se prefiere un TC tipo devanado?',{'Cuando se manejan corrientes primarias bajas o medias y se necesita mayor precision en la medicion.','Cuando se manejan corrientes primarias muy altas y no se exige demasiada precision en la medicion.','Cuando se requiere medir tension en lugar de corriente.','Cuando el conductor de linea es de gran seccion y no puede enrollarse.'},1,'El TC tipo devanado conviene con corrientes primarias bajas o medias, donde se puede tener primario de varias espiras y mayor precision. El distractor de corrientes muy altas corresponde al tipo barra, que se prefiere justamente en ese caso.',false,'';
 't2p10','Medicion TP y TC','Por que no debe dejarse abierto el secundario de un TC energizado?',{'Aumenta el flujo contrario en el nucleo, el flujo se anula por completo y la corriente primaria se dispara de inmediato sin control.','Desaparece el flujo contrario, el flujo aumenta y se inducen voltajes muy altos que danan el aislamiento y son peligrosos.','Se reduce el flujo en el nucleo y el secundario queda sin tension alguna.','Aparece una corriente elevada por el secundario que funde el fusible de proteccion.'},2,'Al abrir el secundario desaparece la fuerza magnetomotriz que se opone al flujo, el flujo crece y se inducen tensiones peligrosas. El distractor que dice que el flujo se anula invierte el fenomeno y por eso es falso.',false,'';
 't2p11','Medicion TP y TC','Por que es importante la precision en estos transformadores?',{'Porque un error en la relacion de transformacion o en el angulo de fase mejora notablemente la exactitud de las mediciones de energia y de potencia.','Porque la precision determina la frecuencia de operacion del sistema electrico.','Porque un error en la relacion de transformacion o en el angulo de fase altera las mediciones de energia y el funcionamiento de los sistemas de proteccion.','Porque la precision fija la potencia maxima que puede transportar la linea.'},3,'Los errores de relacion o de angulo de fase desvirtuan la medicion de energia y pueden hacer operar mal las protecciones. El distractor que afirma que esos errores mejoran la exactitud es falso porque el error siempre degrada la medicion.',false,'';
 't2p12','Medicion TP y TC','Que lecturas se pueden obtener con los transformadores de medicion?',{'Solamente tension y corriente de la red, sin posibilidad alguna de calcular potencias ni energia a partir de ellas en ningun caso.','Tension y corriente de la red, y a partir de ellas potencia activa, potencia reactiva y energia consumida.','Potencia activa y reactiva directamente, sin medir tension ni corriente.','Frecuencia y angulo de fase de la red, sin tension ni corriente.'},2,'Con los transformadores de medicion se leen tension y corriente, y de ahi se calculan potencias y energia. El distractor que los limita a tension y corriente es falso porque precisamente esas lecturas permiten calcular la potencia.',false,'';
 't3p01','Aislamiento','Que dos funciones principales cumple el liquido dielectrico en un transformador con aislamiento liquido?',{'Generar el campo magnetico y amortiguar las vibraciones.','Aislar electricamente los componentes y retirar el calor.','Lubricar el nucleo y filtrar las armonicas de la red.','Aislar electricamente los componentes y aumentar la potencia nominal.'},2,'El liquido dielectrico aisla los componentes y retira el calor que se genera en servicio. El distractor que le suma aumentar la potencia nominal es falso porque la potencia la fija el diseno electromagnetico, no el fluido.',false,'';
 't3p02','Aislamiento','Segun el documento, cual es la principal desventaja del aceite mineral como liquido aislante?',{'Es inflamable y puede contaminar el ambiente.','Es biodegradable y resiste mejor el fuego.','Tiene baja rigidez dielectrica y no enfria el equipo.','Es inflamable pero no representa riesgo ambiental.'},1,'El aceite mineral es la opcion tradicional pero es inflamable y puede contaminar el ambiente si se derrama. El distractor que lo llama biodegradable describe al ester natural, no al aceite mineral.',false,'';
 't3p03','Aislamiento','Por que se considera al ester natural una alternativa mas segura que el aceite mineral?',{'Es biodegradable y contamina menos, pero arde con mayor facilidad.','Es biodegradable y resiste mejor el fuego.','Tiene menor punto de inflamacion y mayor toxicidad que el mineral.','Es mas economico y requiere menos mantenimiento.'},2,'El ester natural es biodegradable y tiene mayor resistencia al fuego que el aceite mineral. El distractor que acepta la biodegradabilidad pero le atribuye arder con mayor facilidad es falso porque justamente tiene un punto de inflamacion mas alto.',false,'';
 't3p04','Aislamiento','Que gas utilizan principalmente los transformadores con aislamiento gaseoso?',{'Hexafluoruro de azufre, conocido como SF6.','Nitrogeno seco, conocido como N2.','Dioxido de carbono, conocido como CO2.','Aire comprimido, conocido como AC.'},1,'El aislamiento gaseoso usa hexafluoruro de azufre, el SF6, por su alta rigidez dielectrica. El nitrogeno seco se emplea en algunos equipos, pero no es el gas principal de esta tecnologia.',false,'';
 't3p05','Aislamiento','Menciona dos ventajas del aislamiento gaseoso frente al aislamiento liquido.',{'No es inflamable y ocupa menos espacio.','Es inflamable y requiere mayor espacio.','No es inflamable pero necesita mas espacio que el liquido.','Es mas economico y no requiere estanqueidad.'},1,'El aislamiento gaseoso no es inflamable y permite equipos mas compactos que el aislamiento liquido. El distractor que admite que no es inflamable pero le atribuye ocupar mas espacio es falso: el gas permite reducir el espacio.',false,'';
 't3p06','Aislamiento','Cual es la "paradoja ambiental" del SF6 mencionada en el documento?',{'Es un gas noble que no afecta al ambiente.','Es biodegradable y no tiene efecto invernadero.','Es un gas inflamable que contamina el suelo.','Es un potente gas de efecto invernadero.'},4,'La paradoja es que el SF6 es excelente aislamiento pero tambien un gas de efecto invernadero muy potente. El distractor que lo declara inofensivo para el ambiente niega justamente esa paradoja.',false,'';
 't3p07','Aislamiento','Que significa la sigla GDWF en los sistemas de refrigeracion de transformadores con gas?',{'Circulacion natural del gas y del agua.','Circulacion forzada del gas y del aceite.','Generacion directa de vapor y fluido.','Circulacion forzada del gas y del agua.'},4,'GDWF indica circulacion forzada del gas y del agua en el sistema de refrigeracion. El distractor que la cambia por circulacion natural falla porque la sigla implica flujo forzado, no natural.',false,'';
 't3p08','Aislamiento','Con que materiales se aislan los devanados en un transformador de tipo seco?',{'Con aceite mineral y papel kraft impregnado.','Con gas SF6 a presion y resinas liquidas de impregnacion al vacio.','Con materiales conductores como cobre y aluminio.','Con materiales dielectricos solidos como epoxi o polimeros.'},4,'El transformador seco aisla los devanados con solidos como epoxi o polimeros, sin liquido. El distractor de aceite y papel kraft corresponde al transformador sumergido, que es la tecnologia opuesta.',false,'';
 't3p09','Aislamiento','Que proceso de fabricacion caracteriza a los transformadores secos tipo VPI?',{'Impregnacion a presion de vacio con poliester.','Impregnacion a presion atmosferica con aceite mineral.','Secado al aire y barnizado superficial con resina.','Inyeccion de gas SF6 en el nucleo ferromagnetico.'},1,'El proceso VPI impregna los devanados a presion de vacio con poliester, lo que sella y aisla el conjunto. El distractor de impregnacion con aceite mineral no aplica al tipo seco.',false,'';
 't3p10','Aislamiento','Por que los transformadores de tipo seco son adecuados para hospitales y edificios?',{'Aumentan el riesgo de incendio y de fugas de aceite.','Reducen el riesgo de incendio pero requieren aceite aislante.','Eliminan las perdidas por histeresis y por corrientes de Foucault.','Reducen el riesgo de incendio y fugas.'},4,'Al no usar liquido inflamable, el transformador seco reduce el riesgo de incendio y de fugas, por eso se prefiere en hospitales y edificios. El distractor que le atribuye eliminar las perdidas magneticas es falso porque esas perdidas dependen del nucleo.',false,'';
 't3p11','Aislamiento','Cual es una limitacion importante de los transformadores secos frente a los de aceite?',{'Disipan mas calor porque el aire conduce mejor que el aceite.','Disipan menos calor porque usan aire.','Disipan menos calor porque el aceite conduce peor que el aire.','No pueden operar en interiores porque el aire es inflamable.'},2,'El transformador seco disipa menos calor porque el aire enfria peor que el aceite, lo que limita su potencia. El distractor que afirma lo contrario invierte la comparacion entre aire y aceite.',false,'';
 't3p12','Aislamiento','Segun las conclusiones, de que factores depende la eleccion del tipo de transformador?',{'Solo la potencia y el costo del equipo.','Frecuencia, fase y factor de potencia de la carga.','Potencia, espacio, seguridad, costo y ambiente.','Tension, corriente y numero de espiras del devanado.'},3,'La eleccion depende de la potencia, el espacio, la seguridad, el costo y el ambiente. El distractor que la reduce solo a potencia y costo es incompleto y por eso no responde lo que concluye el documento.',false,'';
 't4p01','Conexiones trifasicas','1 ventaja y 1 desventaja de la conexion Delta-Delta.',{'Puede manejar cargas trifasicas de alta corriente, pero no proporciona neutro para cargas fase-neutro.','Puede manejar cargas de alta corriente y ademas proporciona neutro para cargas fase-neutro.','No puede manejar cargas de alta corriente y proporciona neutro, por lo que sirve para cargas fase-neutro.','Puede manejar cargas de alta corriente, pero solo si el neutro esta bien conectado a tierra.'},1,'La delta-delta maneja corrientes altas pero no ofrece neutro, por eso no sirve bien para cargas fase-neutro. El distractor que le agrega un neutro es falso porque esa conexion carece de punto neutro.',false,'';
 't4p02','Conexiones trifasicas','Razon por la cual se aplican en industria.',{'Los motores monofasicos requieren poca potencia y esta es la mejor manera de suministrarla.','Las cargas de alumbrado requieren tension fase-neutro y esta es la mejor manera de suministrarla.','Los motores trifasicos requieren una alta potencia y esta es la mejor manera de suministrarla.','Los motores trifasicos requieren baja potencia y esta es la mejor manera de suministrarla.'},3,'La conexion se aplica en industria porque los motores trifasicos demandan alta potencia y esta configuracion la suministra eficientemente. El distractor que cambia trifasicos por monofasicos invierte el tipo de carga tipica.',false,'';
 't4p03','Conexiones trifasicas','Caracteristica de la conexion Y-Y (estrella-estrella)',{'Se utilizan 3 conductores, uno por cada fase, sin conductor neutro.','Se utilizan 4 conductores, todos ellos de fase, uno por cada fase, sin ningun conductor neutro instalado en el sistema.','Se utilizan 4 conductores, uno para la fase A, uno para la fase B, uno para la fase C y uno para el neutro.','Se utilizan 2 conductores, uno de fase y uno de neutro.'},3,'La Y-Y emplea cuatro conductores: tres de fase y uno de neutro. El distractor que usa cuatro conductores todos de fase y sin neutro es falso porque en la estrella el cuarto conductor es precisamente el neutro.',false,'';
 't4p04','Conexiones trifasicas','2 ventajas de la conexion Y-Y.',{'Permite disponer de neutro solo en el secundario y obtener un unico nivel de tension entre las lineas del sistema completo.','No permite disponer de neutro y obliga a usar solo tension entre lineas.','Permite disponer de neutro en ambos lados, pero solo un nivel de tension entre lineas.','Permite disponer de un neutro en ambos lados y obtener dos niveles de tension, entre lineas y entre linea y neutro.'},4,'La Y-Y da neutro en ambos lados y dos niveles de tension, lo que facilita alimentar cargas monofasicas y trifasicas. El distractor que niega el neutro es falso porque la estrella si lo proporciona.',false,'';
 't4p05','Conexiones trifasicas','2 desventajas de la conexion Y-Y.',{'Con cargas equilibradas las tensiones de fase se desequilibran de todos modos, y si el neutro esta bien a tierra el punto neutro se desplaza.','Con cargas desequilibradas las tensiones de fase se desequilibran, y si el neutro no esta bien a tierra el punto neutro se desplaza.','Con cargas desequilibradas las tensiones se mantienen equilibradas, y el neutro a tierra inestabiliza el sistema.','Con cargas desequilibradas se desequilibran las tensiones, pero el neutro a tierra impide todo desplazamiento.'},2,'Con cargas desequilibradas y un neutro mal puesto a tierra, las tensiones de fase se desbalancean y el neutro se desplaza. El distractor que cambia cargas desequilibradas por equilibradas cae porque con carga equilibrada la Y-Y no presenta ese problema.',false,'';
 't4p06','Conexiones trifasicas','Ventaja economica de utilizar una conexion en estrella (Y)',{'En cada devanado recibe una mayor tension lo que obliga a usar conductores mas delgados.','En cada devanado recibe una menor tension lo que obliga a usar conductores mas gruesos y encarece notablemente todo el equipo.','La corriente de linea es menor y por eso se pueden usar conductores mas delgados.','En cada devanado recibe una menor tension lo que permite utilizar conductores mas delgados y ahorrar dinero.'},4,'En la estrella cada devanado soporta tension de fase, menor que la de linea, lo que permite conductores mas delgados y ahorro. El distractor que habla de menor corriente de linea es falso porque en la estrella la corriente de linea es igual a la de fase.',true,'Esta es la respuesta que se espera en el examen. La teoria dice otra cosa: la seccion del conductor la fija la CORRIENTE, no la tension, y en estrella la corriente de fase es la de linea. Lo que ahorra la estrella es aislamiento y espiras, no cobre de seccion. Revisalo en el simulador.';
 't4p07','Conexiones trifasicas','Que provoca el cambio de estrella-delta?',{'Un aumento permanente y sostenido de la frecuencia de operacion de toda la red electrica.','Oscilaciones de tension y corriente afectando la estabilidad de la red electrica.','La eliminacion total de las armonicas de la red.','Una reduccion del nivel de aislamiento requerido.'},2,'El cambio de estrella a delta produce oscilaciones de tension y corriente que afectan la estabilidad de la red. El distractor que habla de un aumento permanente de frecuencia es falso porque el transformador no cambia la frecuencia.',false,'';
 't4p08','Conexiones trifasicas','Por que se emplea esta conexion en sistema de distribucion electrica industrial?',{'Se emplea para proteger la red de caidas de tension y evitar problemas de sobre corriente.','Se emplea para provocar caidas de tension y aumentar la sobrecorriente en toda la red industrial.','Se emplea para elevar la frecuencia y reducir la potencia reactiva.','Se emplea para aislar galvanicamente la red y eliminar el neutro.'},1,'La conexion se usa para proteger la red frente a caidas de tension y sobrecorrientes. El distractor que invierte el proposito y le hace provocar esos problemas es falso por definicion.',false,'';
 't4p09','Conexiones trifasicas','Que armonicas se filtran en el devanando primario?',{'El devanado primario al estar en estrella atrapa las armonicas del tercer orden y evita que regresen a la red.','El devanado primario al estar en delta atrapa las armonicas de quinto orden y evita que regresen a la red.','El devanado primario al estar en delta deja pasar las armonicas del tercer orden hacia la red.','El devanado primario al estar en delta atrapa las armonicas del tercer orden y evita que regresen a la red.'},4,'La respuesta del curso indica que el devanado primario en delta atrapa las armonicas de tercer orden y las aleja de la red. El distractor que las deja pasar a la red invierte el efecto que se pide senalar.',true,'Esta es la respuesta que se espera en el examen. La teoria dice otra cosa: en una Y-D el primario es la estrella, y el devanado que atrapa y hace circular las corrientes de tercer armonico es la DELTA, que ahi es el secundario. Revisalo en el simulador.';
 't4p10','Conexiones trifasicas','2 desventajas de la conexion estrella- delta.',{'Existe un desfase de 60 grados entre primario y secundario, y el devanado primario se calienta por las armonicas.','Existe un desfase de 30 grados y el devanado secundario se enfria por las corrientes armonicas.','Existe un desfase de 30 grados entre primario y secundario, y el devanado primario se calienta por conservar las corrientes armonicas.','No existe desfase y el devanado primario se calienta por las corrientes armonicas.'},3,'La fuente senala como desventajas el desfase de 30 grados y el calentamiento del primario por conservar armonicas. El distractor que cambia el desfase a 60 grados falla porque el desfase tipico de la conexion es de 30 grados.',true,'Esta es la respuesta que se espera en el examen. La teoria dice otra cosa: en una Y-D el primario es la estrella, y el devanado que atrapa y hace circular las corrientes de tercer armonico es la DELTA, que ahi es el secundario. Revisalo en el simulador.';
 't4p11','Conexiones trifasicas','En que caso se emplea?',{'En sistemas de distribucion en transformadores de baja para bajar de media tension a baja tension.','En transformadores de transmision de energia para subir de baja tension a media tension en toda la red.','En transformadores de instrumento para medir tensiones de linea.','En autotransformadores para interconectar dos niveles de alta tension.'},1,'La conexion se emplea en distribucion, en transformadores que bajan de media a baja tension. El distractor que la ubica en transmision subiendo tension corresponde a otra aplicacion.',false,'';
 't4p12','Conexiones trifasicas','Por que se puede utilizar en redes con cargas desequilibradas?',{'Debido a que posee un punto neutro inestable del lado del primario que absorbe por completo el desequilibrio de la carga conectada.','Debido a que carece de neutro y las corrientes desequilibradas se anulan solas.','Debido a que posee un punto neutro estable del lado del secundario permite un retorno de las corrientes que presenten un desequilibrio.','Debido a que el neutro del secundario no permite el retorno de corrientes desequilibradas.'},3,'El lado secundario tiene un neutro estable que da retorno a las corrientes desequilibradas. El distractor que dice que el neutro no permite ese retorno contradice la razon por la que la conexion sirve en esas redes.',true,'Esta es la respuesta que se espera en el examen. La teoria dice otra cosa: en una Y-D el secundario es la delta y una delta no tiene neutro. La delta si estabiliza el neutro, pero el de la ESTRELLA, que ahi es el primario. Revisalo en el simulador.';
 't5p01','Otras conexiones','Como se conectan las bobinas del secundario en un transformador Zig-Zg?',{'Dos secciones conectadas en paralelo, ambas en la misma columna del nucleo magnetico.','Dos secciones en serie, en columnas diferentes del nucleo.','Tres secciones en serie, una por cada columna del nucleo.','Una sola seccion continua sobre una columna del nucleo.'},2,'El secundario en zig-zag se arma con dos secciones en serie ubicadas en columnas distintas del nucleo. El distractor que las pone en paralelo en la misma columna invierte tanto la conexion como la ubicacion.',false,'';
 't5p02','Otras conexiones','Diferencia principal entre conexion Y-Z y Delta-Z?',{'La unica diferencia es la conexion del embobinado secundario.','La diferencia esta en el numero de transformadores monofasicos empleados.','La unica diferencia es la conexion del embobinado primario.','La diferencia esta en el desfase de 90 grados entre sus salidas.'},3,'Entre Y-Z y delta-Z solo cambia como se conecta el primario, porque el secundario en zig-zag es el mismo. El distractor que apunta al secundario es falso, ya que en ambas configuraciones el secundario es identico.',false,'';
 't5p03','Otras conexiones','Para que se usa la conexion trifasica Zig-Zag sin neutro?',{'Para eliminar por completo el neutro artificial y operar unicamente entre las lineas del sistema.','Para crear un punto neutro artificial que funcione como tierra.','Para obtener un desfase de 90 grados entre las fases.','Para reducir la capacidad del banco a un 57.7 por ciento.'},2,'La Zig-Zag sin neutro crea un punto neutro artificial que puede usarse como tierra. El distractor que la usa para eliminar el neutro contradice su proposito, que es precisamente generarlo.',false,'';
 't5p04','Otras conexiones','Cuantos transformadores usan la configuracion "Delta abierta"?',{'3 transformadores monofasicos en lugar de 2.','2 transformadores trifasicos en lugar de 3.','1 transformador monofasico en lugar de 2.','2 transformadores monofasicos en lugar de 3.'},4,'La delta abierta usa dos transformadores monofasicos en lugar de tres. El distractor que habla de dos transformadores trifasicos es falso porque un transformador trifasico no es la unidad de esta configuracion.',false,'';
 't5p05','Otras conexiones','Que capacidad (en porcentaje) tiene un "Delta abierta" comparada con un "Delta cerrada"?',{'La capacidad equivale al 57.7% del total.','La capacidad equivale al 86.6% del total.','La capacidad equivale al 66.6% del total.','La capacidad equivale al 100% del total.'},1,'La delta abierta entrega alrededor del 57.7 por ciento de la capacidad de la delta cerrada. El distractor del 86.6 por ciento es tentador porque surge de otra relacion trigonometrica, pero no es el valor de capacidad de esta conexion.',false,'';
 't5p06','Otras conexiones','Como se llaman las configuraciones que usan dos transformadores para cargas monofasicas y trifasicas con una fase menos?',{'Configuracion estrella abierta y delta abierta.','Configuracion delta cerrada y estrella cerrada.','Configuracion Scott y Zig-Zag.','Configuracion Y-Y y Delta-Delta.'},1,'Las configuraciones que operan con una fase menos son la estrella abierta y la delta abierta. El distractor que nombra Scott y Zig-Zag corresponde a otras conexiones especiales, no a las de fase reducida.',false,'';
 't5p07','Otras conexiones','Como se llaman los 2 transformadores de la conexion tipo Scott?',{'Transformador principal y transformador de arranque.','Transformador auxiliar y transformador de medida.','Transformador principal y transformador auxiliar o teaser.','Transformador teaser y transformador de potencia de la subestacion.'},3,'En la conexion Scott los dos transformadores se llaman principal y auxiliar o teaser. El distractor que los llama de arranque y de medida confunde estos nombres con funciones de otras maquinas.',false,'';
 't5p08','Otras conexiones','Que desfase tienen las tensiones de salida en una conexion Scott?',{'Produce tensiones secundarias separadas por 90 grados.','Produce tensiones secundarias separadas por 30 grados.','Produce tensiones secundarias separadas por 60 grados.','Produce tensiones secundarias separadas por 120 grados.'},1,'La conexion Scott entrega dos tensiones secundarias en cuadratura, separadas 90 grados. El distractor de 120 grados es tentador por ser un desfase trifasico tipico, pero no corresponde a la salida bifasica de Scott.',false,'';
 't5p09','Otras conexiones','Para que ayuda la disposicion de los embobinados en zigzag?',{'Ayuda a mantener un neutro mas estable y a la vez bloquea por completo el camino de las corrientes de secuencia cero.','Ayuda a desestabilizar el neutro y desviar las corrientes de secuencia cero.','Ayuda a mantener un neutro mas estable y proporciona un camino adecuado para corrientes de secuencia cero.','Ayuda a eliminar el neutro artificial y las corrientes de secuencia cero.'},3,'El zigzag estabiliza el neutro y ofrece un camino para las corrientes de secuencia cero. El distractor que lo hace bloquear ese camino invierte justamente la propiedad que se busca.',false,'';
 't5p10','Otras conexiones','Cual es el principal proposito de un sistema de delta abierta?',{'Permitir que, si dos de los tres transformadores se averian, el banco siga funcionando como delta abierto.','Aumentar la capacidad del banco hasta el 100 por ciento cuando falla un transformador.','Convertir automaticamente el banco en estrella abierta al fallar un transformador.','Permitir que, si uno de los tres transformadores de un delta cerrado se averia, el banco siga funcionando como delta abierto.'},4,'La delta abierta permite seguir operando con dos transformadores cuando uno del banco cerrado falla. El distractor que exige que fallen dos transformadores es falso porque con dos averiados ya no queda banco suficiente.',false,'';
 't5p11','Otras conexiones','Como se le conoce a la configuracion que utiliza una fase menos en el primario y es un arreglo de transformadores monofasicos que permite alimentar cargas monofasicas y trifasicas?',{'Transformador con configuracion delta cerrada - estrella cerrada.','Transformador con configuracion Scott - Zig-Zag para cargas especiales de laboratorio.','Transformador con configuracion estrella abierta - delta abierta.','Transformador con configuracion Y-Y - Delta-Delta.'},3,'La configuracion descrita es la estrella abierta - delta abierta, que usa una fase menos en el primario. El distractor que nombra Scott - Zig-Zag mezcla dos conexiones especiales distintas y no corresponde.',false,'';
 't5p12','Otras conexiones','Cuales son las desventajas de una conexion de tipo Scott?',{'Requiere exactamente la misma construccion y conexion que una configuracion trifasica convencional de distribucion.','Requiere una construccion y conexion totalmente distinta a una configuracion trifasica convencional.','No requiere transformadores especiales ni conexiones distintas.','Requiere un autotransformador variable tipo Variac para operar.'},2,'La desventaja de la conexion Scott es que exige una construccion y un conexionado muy distintos de los de una configuracion trifasica convencional. El distractor que dice que no requiere nada especial niega esa desventaja.',false,'';
 't6p01','Autotransformador','Que es un autotransformador?',{'Es una maquina electrica rotativa con dos devanados separados y aislados sobre un nucleo ferromagnetico comun.','Es una maquina electrica estatica con dos devanados aislados entre si.','Es una maquina electrica estatica con un unico devanado continuo enrollado sobre un nucleo ferromagnetico.','Es un dispositivo electronico con un unico devanado sobre un nucleo de aire.'},3,'El autotransformador es una maquina estatica con un solo devanado continuo sobre un nucleo ferromagnetico. El distractor que lo describe como maquina rotativa con dos devanados confunde al autotransformador con un transformador convencional o con una maquina giratoria.',false,'';
 't6p02','Autotransformador','Que es el devanado comun en un autotransformador?',{'Devanado exclusivo del circuito primario, completamente aislado del circuito secundario.','Devanado exclusivo del circuito secundario, aislado del primario.','Devanado de arranque que solo opera durante el encendido.','Devanado compartido simultaneamente por el circuito primario y secundario.'},4,'El devanado comun es la porcion que comparten a la vez el primario y el secundario. El distractor que lo hace exclusivo de uno de los circuitos contradice la definicion de devanado comun.',false,'';
 't6p03','Autotransformador','Cual es una ventaja principal del autotransformador?',{'Tiene menor tamano, menor costo y mayor eficiencia.','Tiene mayor tamano, mayor costo y menor eficiencia.','Tiene menor tamano, mayor costo y menor eficiencia.','Tiene mayor tamano, menor costo y mayor eficiencia.'},1,'El autotransformador es mas compacto, mas barato y mas eficiente que el transformador convencional de igual potencia. Los distractores intercambian esas tres propiedades para volverlas falsas.',false,'';
 't6p04','Autotransformador','Cuales son las dos formas de transferir energia de un autotransformador?',{'Por acoplamiento magnetico y aislamiento galvanico total.','Por conduccion electrica y aislamiento galvanico total.','Por acoplamiento magnetico y conexion galvanica directa.','Por acoplamiento capacitivo y conexion galvanica directa.'},3,'El autotransformador transfiere energia por acoplamiento magnetico y tambien por conexion galvanica directa entre sus partes. El distractor que menciona aislamiento galvanico total es falso porque el autotransformador justamente no lo tiene.',false,'';
 't6p05','Autotransformador','Cual es la principal limitacion de un autotransformador?',{'Pierde el aislamiento galvanico entre entrada y salida.','Conserva el aislamiento galvanico entre entrada y salida.','Gana aislamiento galvanico pero pierde eficiencia.','Pierde el acoplamiento magnetico entre entrada y salida.'},1,'La principal limitacion es que no existe aislamiento galvanico entre entrada y salida, por la conexion directa. El distractor que dice que conserva ese aislamiento contradice la limitacion misma.',false,'';
 't6p06','Autotransformador','Que diferencia estructural tiene un autotransformador frente al transformador convencional?',{'Tiene dos devanados independientes sobre nucleos separados.','Tiene un unico devanado continuo sobre un nucleo comun.','Tiene dos devanados independientes sobre un nucleo comun.','Tiene un unico devanado sobre un nucleo de aire.'},2,'La diferencia estructural es que usa un solo devanado continuo sobre un nucleo comun. El distractor de dos devanados independientes describe al transformador convencional, que es justamente lo que se compara.',false,'';
 't6p07','Autotransformador','Que representa la potencia SW en el autotransformador?',{'Representa la potencia total entregada a la carga en el secundario.','Representa la potencia manejada fisicamente por los devanados.','Representa la potencia perdida por calentamiento en el nucleo.','Representa la potencia reactiva consumida por la carga.'},2,'La potencia SW es la que manejan fisicamente los devanados del autotransformador. El distractor que la iguala a la potencia total de la carga es falso porque esa es mayor: incluye tambien la potencia transferida por conexion.',false,'';
 't6p08','Autotransformador','Por que razon la corriente cortocircuito del autotransformador es mayor?',{'La impedancia porcentual es mayor que la de un transformador convencional.','La impedancia porcentual es menor que la de un transformador convencional.','La impedancia porcentual es igual a la de un transformador convencional.','La resistencia de los devanados es mayor que la de un transformador convencional.'},2,'La corriente de cortocircuito es mayor porque la impedancia porcentual del autotransformador es menor que la del convencional. El distractor que la hace mayor invierte la relacion y por eso no explica la corriente elevada.',false,'';
 't6p09','Autotransformador','2 principales aplicaciones de los autotransformadores',{'Interconexiones de sistemas de transmision a dos niveles de tension muy distantes y proteccion de lineas de alta tension.','Reguladores de tension en redes de transmision y proteccion contra cortocircuitos.','Medicion de tension y corriente en subestaciones de alta tension.','Interconexiones de sistemas de transmision a dos niveles de tension proximos y reguladores de tension en redes de distribucion.'},4,'Las dos aplicaciones principales son interconectar niveles de tension proximos y regular tension en distribucion. El distractor que lo destina a medicion corresponde a los transformadores de instrumento, no al autotransformador.',false,'';
 't6p10','Autotransformador','Cuantas conexiones posee un autotransformador?',{'Solamente elevador y reductor monofasico, sin Variac ni arranque.','Solamente conexiones trifasicas, sin version monofasica ni Variac.','Elevador y reductor monofasico, variable o Variac, de arranque para motores trifasicos y conexiones trifasicas.','Elevador reductor, variable o Variac y de arranque monofasico, pero sin ninguna conexion trifasica disponible en el mercado.'},3,'El autotransformador admite versiones elevadora y reductora, variable, de arranque y conexiones trifasicas. El distractor que lo limita a una sola familia omite conexiones que la fuente si lista.',false,'';
 't6p11','Autotransformador','Que buscan los autotransformadores en acoplamientos de impedancias en circuitos electronicos?',{'Buscan la minima transferencia de energia dentro de las diferentes etapas.','Buscan aislar galvanicamente las etapas y evitar por completo la transferencia de energia entre ellas.','Buscan la maxima transferencia de energia dentro de las diferentes etapas.','Buscan reducir la frecuencia de la senal entre etapas.'},3,'En el acoplamiento de impedancias se busca la maxima transferencia de energia entre etapas. El distractor que busca la minima transferencia contradice el objetivo del acoplamiento.',false,'';
 't6p12','Autotransformador','En el arranque de motores, que tipo de autotransformador es utilizado?',{'Un autotransformador monofasico con una sola derivacion porque eleva la tension aplicada al motor durante el arranque para limitar la corriente de linea.','Un autotransformador trifasico con varias derivaciones porque eleva la tension aplicada al motor durante el arranque.','Un autotransformador trifasico sin derivaciones porque mantiene la tension aplicada al motor durante el arranque.','Un autotransformador trifasico con varias derivaciones porque reduce la tension aplicada al motor durante el arranque para limitar corriente.'},4,'En el arranque se usa un autotransformador trifasico con derivaciones que reduce la tension aplicada al motor para limitar la corriente. El distractor que dice que eleva la tension es falso porque el arranque necesita reducirla.',false,'';
};

B = repmat(struct('id','','tema','','enunciado','','opciones',{{}}, ...
    'correcta',1,'explicacion','','bandera',false,'advertencia',''),1,size(C,1));
for k = 1:size(C,1)
    B(k).id          = C{k,1};
    B(k).tema        = C{k,2};
    B(k).enunciado   = C{k,3};
    B(k).opciones    = C{k,4};
    B(k).correcta    = C{k,5};
    B(k).explicacion = C{k,6};
    B(k).bandera     = C{k,7};
    B(k).advertencia = C{k,8};
end
end
